export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const FETCH_ALL_USERS_FAILURE = 'FETCH_ALL_USERS_FAILURE';

export const FETCH_USER_BY_EMAIL = 'FETCH_USER_BY_EMAIL';
export const FETCH_USER_BY_EMAIL_SUCCESS = 'FETCH_USER_BY_EMAIL_SUCCESS';
export const FETCH_USER_BY_EMAIL_FAILURE = 'FETCH_USER_BY_EMAIL_FAILURE';

export const UPDATE_PRIMARY_COLOR = 'UPDATE_PRIMARY_COLOR';
export const UPDATE_PRIMARY_COLOR_SUCCESS = 'UPDATE_PRIMARY_COLOR_SUCCESS';
export const UPDATE_PRIMARY_COLOR_FAILURE = 'UPDATE_PRIMARY_COLOR_FAILURE';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
